#!/usr/bin/python3
import numpy as np

def sieve_of_eratosthenes(val):
  max = val+1
  lst = [True] * max
  for i in range(2, int(val**0.5 + 1)):
    if lst[i]:
      for j in range(i*i, max, i):
        lst[j] = False
  final = []
  for i in range(2, max):
    if lst[i]:
      final.append(i)
  return final



for x in range(4,202,2):
	y = sieve_of_eratosthenes(x)
	new_primes = []
	chi_set =[]
	for t in y:
		if (t >= x/2 and t< x-1):
			new_primes.append(t)
		
	for p in new_primes:
		chi_set.append(x-p)
	print(x, ":", chi_set, )
